### ISSUE TITLE
Forces of Evil sometimes seek alliances with Free Peoples

### ISSUE THREAD

**Issue by jj248** [CK3RealmsinExile/RealmsInExile#170]
https://discord.com/channels/751097183448727552/778645689089392730/898175711322460171

**Comment by jj248** [comment]
Ready to test - it should be pretty much impossible to secure an alliance with a character of a faith that views your faith as evil.

**Comment by Remerod** [comment]
How would be the best way to test this? Force a marriage between two opposite religions rulers familly and see if it'll form an alliance or not? Or/and any other ways?

**Comment by JukeJukestar** [comment]
Note that the second perk in the diplomacy skill tree gives the option to negotiate an alliance without a marriage. Sauron likes to propose this castamiri gondor as they are astray from him (kingsmen)

**Comment by JukeJukestar** [comment]
just thought of a solution - have the special character decision to make an alliance without blood ties restricted so if youre faithful you cant use it against evil faiths and if youre evil you cant use it against faithful

men of darkness should be open to both regardless of heritage

**Comment by Remerod** [comment]
I think this is fixed in my opinion, i've really never seen an alliance between good and evil in the longest of times 

![image](https://user-images.githubusercontent.com/79544635/155859989-c1ab520c-1f97-4c9c-84b5-0ece4b4d91df.png)

![image](https://user-images.githubusercontent.com/79544635/155860012-6c8e7107-194a-4e81-b150-d72fd87d7aa5.png)
