### ISSUE TITLE
Crazy Eye Nazgul 

### ISSUE THREAD

**Issue by Remerod** [CK3RealmsinExile/RealmsInExile#270]
There have been some reports by other testers (not me) and now on the bug-reports on discord that at certain event the Nazguls (or at least Golden King) get crazy eyes. I'm not certain how to replicate this occurrence as it's not happened to me. 

![image](https://user-images.githubusercontent.com/79544635/151678091-929c5ec9-3d14-4f64-9e7c-5bc8c29e8bf0.png)

**Comment by BriceLeduc** [comment]
This happens when the Nazgûl is in an event and given the fear animation (and I think shock as well)

**Comment by jj248** [comment]
Any animation that overrides the eye accessory will cause this to happen.

e.g. for fear.  emotion_fear in animations.txt triggers the emotion_fear_decal portrait modifier in animation_expressions.txt to replace the no_eyes accessory with normal_eyes_no_shadow.

Can be fixed by adding an is_nazgul = no trigger or similar to triggers in animations.txt

**Comment by jj248** [comment]
Pushed a fix and ready to test.  Nazgul are now play the angry animation instead of the fear, grief or shock animations.

**Note that Barbershop mod will override this, so needs to be tested using in-game events.**

**Comment by jj248** [comment]
It appears that it still shows in some cases - at least it's better than it was!  We can review in v3.0.

**Comment by jj248** [comment]
I find this amusing enough to defer until v4. :P

**Comment by Jaco-Daan** [comment]
Closing this issue as we haven't seen any related erros.
